---
project_path: /home/mindful/Documents/Unreal\ Projects/Blocks/Blocks.uproject

use_ue_docker: true
custom_ue_path: /home/$USER/EpicGames/UE4.27/Engine/Binaries/Linux/

airsim: true
ros: true

num_simulations: 3
play_time: 60
include_mindful_lib: true
include_python_script: true
