---
project_path: /home/mindful/Documents/Unreal\ Projects/Blocks/Blocks.uproject

use_ue_docker: true
custom_ue_path: /home/$USER/EpicGames/UE4.27/Engine/Binaries/Linux/

airsim_agent: /home/$USER/HeadlessDockerizedClosedloopUE/airsim-ros/sharec/src/waypoint_test_square.py

airsim: true
ros: true

#dictionary of topics to subscribe to and their respective types
topics: {"/mindful_image": "Image", "/mindful_depth": "Image", "/mindful_info": "CameraInfo", "/mindful_pose": "PoseStamped", "/mindful_ground_truth": "String"}
topic-folder: {"/mindful_image": "rgb", "/mindful_depth": "depth", "/mindful_info": ".", "/mindful_pose": ".", "/mindful_ground_truth": "."}
topic-json: {"/mindful_info": "camera.yml", "/mindful_pose": "cameraPosition.yml", "/mindful_ground_truth": "ground_truth.json"}

num_simulations: 3
play_time: 40
include_mindful_lib: true
include_python_script: true

ground_truth_targets: ['"SM_Sedan_01a"','"SM_SUV_01a"']
editor_modifier_script: /home/$USER/HeadlessDockerizedClosedLoopUE/Python/scale_cars.py
